@startuml
class Worker {
    + Id : string? <<get>> <<set>>
    + Deleted : bool? <<get>> <<set>>
    + FirstName : string? <<get>> <<set>>
    + LastName : string? <<get>> <<set>>
    + MidName : string? <<get>> <<set>>
    + DateOfBirthday : DateTime? <<get>> <<set>>
    + NumberPhone : string? <<get>> <<set>>
    + BranchId : Branch? <<get>> <<set>>
    + PayPerHour : double? <<get>> <<set>>
    + TitleView : string? <<get>> <<set>>
    + NumberPhoneView : string? <<get>> <<set>>
    + PayPerHourView : string? <<get>> <<set>>
}
@enduml
