@startuml
class UsersPage <<partial>> {
    + UsersPage()
    # <<override>> OnAppearing() : void
    - <<async>> RefreshData() : void
    - <<async>> AddButton_OnClicked(sender:object?, e:EventArgs) : void
    - <<async>> ListView_OnItemSelected(sender:object?, e:SelectedItemChangedEventArgs) : void
}
ContentPage <|-- UsersPage
@enduml
