@startuml
!include .\\TireServiceApplication\Source\Data\ApiClient.puml
!include .\\TireServiceApplication\Source\Data\AuthenticationData.puml
!include .\\TireServiceApplication\Source\Data\BranchData.puml
!include .\\TireServiceApplication\Source\Data\EquipmentData.puml
!include .\\TireServiceApplication\Source\Data\OrderData.puml
!include .\\TireServiceApplication\Source\Data\Response.puml
!include .\\TireServiceApplication\Source\Data\ServiceData.puml
!include .\\TireServiceApplication\Source\Data\Storage.puml
!include .\\TireServiceApplication\Source\Data\UserData.puml
!include .\\TireServiceApplication\Source\Data\WorkerData.puml
!include .\\TireServiceApplication\Source\Entities\Authentication.puml
!include .\\TireServiceApplication\Source\Entities\Branch.puml
!include .\\TireServiceApplication\Source\Entities\Equipment.puml
!include .\\TireServiceApplication\Source\Entities\Estimated.puml
!include .\\TireServiceApplication\Source\Entities\Order.puml
!include .\\TireServiceApplication\Source\Entities\OrderStatus.puml
!include .\\TireServiceApplication\Source\Entities\Role.puml
!include .\\TireServiceApplication\Source\Entities\Service.puml
!include .\\TireServiceApplication\Source\Entities\User.puml
!include .\\TireServiceApplication\Source\Entities\UserToken.puml
!include .\\TireServiceApplication\Source\Entities\Worker.puml
!include .\\TireServiceApplication\Source\Models\AuthenticationModel.puml
!include .\\TireServiceApplication\Source\Models\BranchModel.puml
!include .\\TireServiceApplication\Source\Models\EquipmentModel.puml
!include .\\TireServiceApplication\Source\Models\OrderModel.puml
!include .\\TireServiceApplication\Source\Models\OrderStatusModel.puml
!include .\\TireServiceApplication\Source\Models\ServiceModel.puml
!include .\\TireServiceApplication\Source\Models\UserModel.puml
!include .\\TireServiceApplication\Source\Models\WorkerModel.puml
!include .\\TireServiceApplication\Source\Pages\Branches\AddBranchPage.xaml.puml
!include .\\TireServiceApplication\Source\Pages\Branches\BranchesPage.xaml.puml
!include .\\TireServiceApplication\Source\Pages\Branches\SettingBranchPage.xaml.puml
!include .\\TireServiceApplication\Source\Pages\Equipments\AddEquipmentPage.xaml.puml
!include .\\TireServiceApplication\Source\Pages\Equipments\EquipmentPage.xaml.puml
!include .\\TireServiceApplication\Source\Pages\Equipments\SettingEquipmentPage.xaml.puml
!include .\\TireServiceApplication\Source\Pages\Orders\AddOrderPage.xaml.puml
!include .\\TireServiceApplication\Source\Pages\Orders\OrdersPage.xaml.puml
!include .\\TireServiceApplication\Source\Pages\Orders\ViewOrderPage.xaml.puml
!include .\\TireServiceApplication\Source\Pages\Others\AuthenticationPage.xaml.puml
!include .\\TireServiceApplication\Source\Pages\Others\MainPage.xaml.puml
!include .\\TireServiceApplication\Source\Pages\Others\SettingsPage.xaml.puml
!include .\\TireServiceApplication\Source\Pages\Others\UrlSettingPage.xaml.puml
!include .\\TireServiceApplication\Source\Pages\Reports\ReportsPage.xaml.puml
!include .\\TireServiceApplication\Source\Pages\Services\AddServicePage.xaml.puml
!include .\\TireServiceApplication\Source\Pages\Services\ServicesPage.xaml.puml
!include .\\TireServiceApplication\Source\Pages\Services\SettingServicePage.xaml.puml
!include .\\TireServiceApplication\Source\Pages\Users\AddUserPage.xaml.puml
!include .\\TireServiceApplication\Source\Pages\Users\SettingUserPage.xaml.puml
!include .\\TireServiceApplication\Source\Pages\Users\UsersPage.xaml.puml
!include .\\TireServiceApplication\Source\Pages\Workers\AddWorkerPage.xaml.puml
!include .\\TireServiceApplication\Source\Pages\Workers\SettingWorkerPage.xaml.puml
!include .\\TireServiceApplication\Source\Pages\Workers\WorkersPage.xaml.puml
@enduml
